server:
  port: 8080
spring:
  application:
    name: my_demo
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
